### ISSUE TITLE
Switch default behavior to auto-publish

### ISSUE THREAD

**Issue by DrewML** [fregante/chrome-webstore-upload-cli#3]
TODO:
- Remove `--auto-publish` flag
- Change behavior of `webstore` (without sub-commands) to do an upload + publish
- ~~Make `upload` command include publishing by default~~
- ~~Add `--no-publish` flag to disable publishing when running `upload` command~~

https://github.com/sindresorhus/refined-github/pull/235#discussion_r65682540

**Comment by sindresorhus** [comment]
Maybe it would be better if `$ webstore` (no sub-command) uploaded and published. If you want either independently, you can use the sub-commands. That way you don't need to flag and the most common use-case get's easier.

**Comment by DrewML** [comment]
👍 I like it. Less complexity, better DX.

**Comment by DrewML** [comment]
@sindresorhus Quick Q for you, since you have more experience writing CLIs than I do.

For the `--help` text, right now we have:

```shell
    Usage
      $ webstore <command>

    where <command> is one of
        upload, publish
```

What kind of verbiage would you expect to see here instead when those are optional, and the default is both?

**Comment by DrewML** [comment]
I've got a branch for this locally. Going to sit on it until #5 is ready so we only have to do a single major version bump.

**Comment by sindresorhus** [comment]
I dunno. Probably something like this:

```
Usage
  $ webstore [command]

Commands
  upload - Description
  publish - Description

When no command is specified it will both upload and publish
```

**Comment by sindresorhus** [comment]
Any movement on this?

**Comment by DrewML** [comment]
Sorry about that, will get to it soon. Have been putting it off in favor of some work on other projects, but definitely want to make it happen.

**Comment by fregante** [comment]
Happy 8-year anniversary!

**Comment by fregante** [comment]
https://github.com/fregante/chrome-webstore-upload-cli/releases/tag/v3.2.0

**Comment by flazouh** [comment]
Hi, any way to upload, submit for review, but not publish?
