### ISSUE TITLE
Support ignoring some files on upload

### ISSUE THREAD

**Issue by fent** [fregante/chrome-webstore-upload-cli#33]
Hi! I thought it would be a good feature to support ignoring some files and directories that are zipped up and uploaded. For example, `node_modules` or `src` directories that are no longer used by the extension after a build step.

**Comment by bfred-it** [comment]
At the moment you just need to put everything into a folder. This also helps you automatically keep all extraneous files out — do you really want to exclude allll your config files explicitly?

At most we could automatically exclude what appears in .gitignore

**Comment by fent** [comment]
Hmm, my workspace is a bit different. The folder is the repo. And one of the dependencies is something I'm working on that I have symlinked to my extension while I'm working on both. And that dependency has webpack and a bunch of other build stuff on it, which adds like 40mb.

I guess for now I can unlink it before I publish.

**Comment by fregante** [comment]
I don't really want to implement/support this logic here. If you want anything more than "zip this whole folder" you can use another archive tool and then pass the output to `chrome-webstore-upload-cli`

It would look something like:

```js
7z ./ a.zip --exclude node_modules && chrome-webstore-upload upload --auto-publish
```

**Comment by J3ekir** [comment]
> I don't really want to implement/support this logic here. If you want anything more than "zip this whole folder" you can use another archive tool and then pass the output to `chrome-webstore-upload-cli`
> 
> It would look something like:
> 
> ```js
> 7z a ./ a.zip --exclude node_modules && chrome-webstore-upload upload --auto-publish
> ```

Why though? `web-ext` has it. My code is like this right now. That folder contains Adobe Illustrator files. Only needed for developement. It's not a mandatory thing but could be useful.

```
- name: Chrome
  env:
    EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
    CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
    REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
  run: |
    mkdir -p .builds
    zip -r .builds/ChromeExtension.zip * -x "img/SVG/*"
    npx chrome-webstore-upload-cli@^3 \
      --source .builds/ChromeExtension.zip \
      --extension-id $EXTENSION_ID \
      --client-id $CLIENT_ID \
      --client-secret $CLIENT_SECRET \
      --refresh-token $REFRESH_TOKEN

- name: Firefox
  env:
    WEB_EXT_API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
    WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
  run: |
    git checkout firefox
    npx web-ext@^8 sign \
      --ignore-files "img/SVG/**" \
      --channel listed \
      --api-key $WEB_EXT_API_KEY \
      --api-secret $WEB_EXT_API_SECRET
```

**Comment by fregante** [comment]
> Why though? `web-ext` has it

`web-ext` has the whole kitchen sink and I don't want that. Look at the dependency tree: https://npmgraph.js.org/?q=web-ext

Before you know it, someone will ask to support `--include` just for specific files, then someone opens a bug about excluding sub-files that appear in `include` and vice versa. This is a solved issue and part of other tools, that can be easily used.

In your case it would be easier to use `rm -rf img/SVG` in both cases just before calling the tool

```diff
	- name: Chrome
	  env:
	    EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
	    CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
	    CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
	    REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
	  run: |
-	    mkdir -p .builds
-	    zip -r .builds/ChromeExtension.zip * -x "img/SVG/*"
+	    rm -rf img/SVG
	    npx chrome-webstore-upload-cli@^3 \
-	      --source .builds/ChromeExtension.zip \
	      --extension-id $EXTENSION_ID \
	      --client-id $CLIENT_ID \
	      --client-secret $CLIENT_SECRET \
	      --refresh-token $REFRESH_TOKEN
	
	- name: Firefox
	  env:
	    WEB_EXT_API_KEY: ${{ secrets.FIREFOX_JWT_ISSUER }}
	    WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
	  run: |
	    git checkout firefox
+	    rm -rf img/SVG
	    npx web-ext@^8 sign \
-	      --ignore-files "img/SVG/**" \
	      --channel listed \
	      --api-key $WEB_EXT_API_KEY \
	      --api-secret $WEB_EXT_API_SECRET
```

**Comment by fregante** [comment]
By the way, you don't need to specify those flags:

```diff
+	    npx chrome-webstore-upload-cli@3
-	    npx chrome-webstore-upload-cli@^3 \
-	      --source .builds/ChromeExtension.zip \
-	      --extension-id $EXTENSION_ID \
-	      --client-id $CLIENT_ID \
-	      --client-secret $CLIENT_SECRET \
-	      --refresh-token $REFRESH_TOKEN
```

They've been deprecated and they'll be removed at some point:

- #80

**Comment by J3ekir** [comment]
It makes a lot more sense now. Thanks for the explanation and the tips.
