### ISSUE TITLE
Looks like upload does not take cwd into account

### ISSUE THREAD

**Issue by stefanbuck** [fregante/chrome-webstore-upload-cli#56]
I just got a weird message while uploading a new version.

```
More than one manifest found in package: assets/manifest.json, dist/manifest.json.
```

https://github.com/OctoLinker/OctoLinker/runs/4073114082?check_suite_focus=true#step:6:18

This is strange, because cwd should be `./dist` and not the checkout root which might be the problem.  

```
cd dist && yarn chrome-webstore-upload upload --auto-publish
```

I tried to replicate the issue locally, but after ~20min waiting for the upload to complete, I got a 500 status back. My suspicion is, it tried to upload my entire local checkout rather than just `./dist` 

However, I was able to upload a new version using `--source ./dist`.

**Comment by fregante** [comment]
It worked for me 🤔 

https://github.com/npmhub/npmhub/blob/f352d89d4d3a911ba68c023e8cee9c7850cdfa8c/.github/workflows/release.yml#L57

**Comment by stefanbuck** [comment]
Mhhh that's odd. I can't spot any difference that explains this behaviour. I'll keep investing

**Comment by fregante** [comment]
Indeed, the only difference I see is the use of `yarn` instead of `npx`. Could that have used the wrong cwd?
