### ISSUE TITLE
PKG_NO_TWO_FACTOR_AUTH

### ISSUE THREAD

**Issue by FezVrasta** [fregante/chrome-webstore-upload-cli#59]
Hi, Google is forcing everybody to use 2FA, is there a way to make this CLI work in this new situation?

Error: PKG_NO_TWO_FACTOR_AUTH
Enabling 2 step verification on your account is required for security purposes. Please visit https://www.google.com/landing/2step to set it up.

**Comment by AprilSylph** [comment]
How new is this? I've had 2FA enabled and this package has worked as late as last Wednesday (2022-01-05).

**Comment by fregante** [comment]
Same for me, I published an old extension as usual just yesterday. I think the error suggests that you enable 2FA, but then the API will continue again after you do. APIs are not affected by 2FA.

**Comment by AprilSylph** [comment]
Yep, still works for me. https://github.com/AprilSylph/XKit-Rewritten/runs/4807835427?check_suite_focus=true

This is not an issue with the package.
