### ISSUE TITLE
Don't add cwd if a full path is already passed

### ISSUE THREAD

**Issue by florian-berger** [fregante/chrome-webstore-upload-cli#68]
We manage our source code in Azure DevOps and also use its pipelines of it for releasing new versions of our Chrome application.

Now, we have a problem with this chrome-webstore-upload-cli package. We are using version 2.0.0 of it and passing a whole path as --source parameter (`D:\a\1\Extension-Upload\Chrome.zip`).
But when executing the script, I get the following output:
```
- Fetching token
- Uploading Chrome.zip
Error
RequestError: ENOENT: no such file or directory, open 'D:\a\1\s\D:\a\1\Extension-Upload\Chrome.zip'
    at Request._destroy (C:\npm\prefix\node_modules\chrome-webstore-upload-cli\node_modules\got\dist\source\core\index.js:1386:21)
    at _destroy (node:internal/streams/destroy:102:25)
    at Request.destroy (node:internal/streams/destroy:64:5)
    at C:\npm\prefix\node_modules\chrome-webstore-upload-cli\node_modules\got\dist\source\core\index.js:354:26
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ENOENT',
  timings: undefined
}
```

A look at the [wrapper.js](https://github.com/fregante/chrome-webstore-upload-cli/blob/main/wrapper.js#L11C3-L11C3) file revealed that `process.cwd()` is always combined with the passed path. This shouldn't be done when a full path is already specified.

**Comment by fregante** [comment]
Good point, I think `join` should be replaced with `resolve`
