### ISSUE TITLE
Publishing not working.

### ISSUE THREAD

**Issue by alexandredepape** [fregante/chrome-webstore-upload-cli#73]
<img width="1055" alt="Screenshot 2023-12-12 at 20 26 46" src="https://github.com/fregante/chrome-webstore-upload-cli/assets/25705704/89f8836d-79bf-4275-9f5d-c17870154dc8">

Despite a successful message, on https://chrome.google.com/u/1/webstore/devconsole/, my package is nor published, nor uploaded.

Do you have a working example from which I can get help.

Thanks in advance.

**Comment by fregante** [comment]
Duplicate of https://github.com/fregante/chrome-webstore-upload/issues/73#issuecomment-1853077673
