### ISSUE TITLE
description too long

### ISSUE THREAD

**Issue by alexandredepape** [fregante/chrome-webstore-upload-cli#75]
<img width="983" alt="Screenshot 2023-12-27 at 10 44 18" src="https://github.com/fregante/chrome-webstore-upload-cli/assets/25705704/77cbdfa0-e039-4cdc-8b47-7d4034c05dab">

Hi do you know what it tells me there is a limit here, do you know how to programmatically set the description without this limit ?

**Comment by fregante** [comment]
Not possible unfortunately

See: https://github.com/fregante/chrome-webstore-upload/issues/71

**Comment by alexandredepape** [comment]
> Not possible unfortunately. The `description` field is used by Chrome, not the store (which usually _**requires**_ more than 132 characters)
> 
> See: https://github.com/fregante/chrome-webstore-upload/issues/71
> 
> 

Awe that sucks.. I have a use case where I need to update my description based on my codebase kind of and had already made it work when encountered the 132 char limit.. how bad is the support for the chrome store it's weird. Is it like that With others browsers too ?

Do you think maybe with a solution with pupetteer like by simulating clicks? I would have to find a way to do the Google log in also.. not sure if feasible

**Comment by fregante** [comment]
> Do you think maybe with a solution with pupetteer like by simulating clicks?

Maybe, but that would be an entirely different tool, not here.
