### ISSUE TITLE
CLI fails on publish in azure pipeline

### ISSUE THREAD

**Issue by demkantor** [fregante/chrome-webstore-upload-cli#77]
##[section]Starting: Chrome Store Publish
==========================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.231.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==========================================================================
Generating script.
Script contents:
chrome-webstore-upload publish --extension-id *** --client-id *** --client-secret *** --refresh-token ***
========================== Starting Command Output ===========================
[command]/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/78da6bae-8a3a-450a-a1bb-55b94fde4653.sh
file:///opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/chrome-webstore-upload-cli/find-source.js:25
     throw new Error(`${errorStart} directory does not contain manifest.json: ${resolvedPath}`);
            ^
Error: Using the cwd, the directory does not contain manifest.json: /home/vsts/work/1/s
  at processDirectory (file:///opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/chrome-webstore-upload-cli/find-source.js:25:15)
  at async getConfig (file:///opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/chrome-webstore-upload-cli/config.js:14:18)
  at async file:///opt/hostedtoolcache/node/20.10.0/x64/lib/node_modules/chrome-webstore-upload-cli/cli.js:60:5

Node.js v20.10.0

##[error]Bash exited with code '1'.
##[section]Finishing: Chrome Store Publish
==========================================================================

The above output happens after successful upload for the past two months or so. Everything worked as expected for the previous year

**Comment by fregante** [comment]
The error is clear, it means it cannot find the manifest. Make sure you're setting the right path
