### ISSUE TITLE
Error: Using the cwd, the directory does not contain manifest.json

### ISSUE THREAD

**Issue by sovetski** [fregante/chrome-webstore-upload-cli#78]
Hi, I am getting this error:

Error: Using the cwd, the directory does not contain manifest.json: /home/runner/work/myextension/myextension

```
- name: Upload step
  run: |-
      chrome-webstore-upload upload --auto-publish \\
        --source chrome-extension-${{ github.sha }}.zip \\
        --extension-id ${{ env.EXTENSION_ID }} \\
        --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \\
        --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \\
        --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
```

The artifact file is: chrome-extension-randomhashhere.zip -> dist -> extension files

It says "using the cwd", but I added "--source" parameter, so I don't understand really.
I think it tries to find the manifest.json on the wrong place, but it looks that the CLI is not taking zip file as a source.

**Comment by fregante** [comment]
I think it's failing on that double-slash, it should be just one

Also you don't need to use it that way, refer to the workflow linked in the readme: https://github.com/fregante/ghatemplates/blob/07486d6753ae0a2e77aa5720ddfd1784c2ac9184/webext/release.yml#L52-L58

**Comment by sovetski** [comment]
@fregante man, a thousand thanks, you just saved my day.
